version: '1'
rules:
  - base: master
    upstream: DIYgod:master
    mergeMethod: hardreset
  - base: dokku
    upstream: DIYgod:master
    mergeMethod: merge
    mergeUnstable: true # prevent non-pass tests from preventing automatic merge
