name: '[docker] CI for releases'

on:
  push:
    branches:
      - dokku
    paths:
      - '.github/workflows/docker-release.yml'
      - 'lib/**'
      - '!**/maintainer.js'
      - '!**/radar.js'
      - '!**/radar-rules.js'
      - 'Dockerfile'
      - 'package.json'
      - 'yarn.lock'
  workflow_dispatch: ~

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (ordinary version)
        id: meta-ordinary
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/rsshub
          tags: |
            type=raw,value=latest,enable=true
            type=sha,enable=true
          flavor: latest=false

      - name: Build and push Docker image (ordinary version)
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta-ordinary.outputs.tags }}
          labels: ${{ steps.meta-ordinary.outputs.labels }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          cache-from: type=gha,scope=docker-release
          cache-to: type=gha,mode=max,scope=docker-release
